[ADD] light tests suite verified on push and before deployment

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -3,14 +3,18 @@
 echo "Lint & Build..."
 
 npm run lint
-
 if [ $? -ne 0 ]; then
   echo "Error : linting failed. Push aborted."
   exit 1
 fi
 
-npm run build
+npm run test:run
+if [ $? -ne 0 ]; then
+  echo "Error : tests failed. Push aborted."
+  exit 1
+fi
 
+npm run build
 if [ $? -ne 0 ]; then
   echo "Error : build failed. Push aborted."
   exit 1
